Check if a process from the pid-file really exists

diff --git a/ts-warp.sh.in b/ts-warp.sh.in
--- a/ts-warp.sh.in
+++ b/ts-warp.sh.in
@@ -48,10 +48,20 @@ FORCE=0                         # Ignore status and start/stop ts-warp forcibly
 # ------------------------------------------------------------------------------
 _start() {
     if [ $FORCE -eq 0 ]; then
-        _status && {
-            printf "ts-warp is already running: "
-            return 0
-        }
+        _status
+        case $? in
+            0)
+                printf "ts-warp is already running: "
+                return 0
+                ;;
+            1)
+                ;;
+            2)
+                printf "ts-warp status unknown: requesting 'force stop'. "
+                FORCE=1
+                _stop
+                ;;
+        esac
     fi
 
     _check_root
@@ -77,37 +87,64 @@ _start() {
     echo $tswarp_options $* | xargs "$tswarp_prefix"/bin/ts-warp > /dev/null
 }
 
+# ------------------------------------------------------------------------------
 _status() {
     # Set $1 if status message is required
-
-    [ -s "$tswarp_pidfile" -a -r "$tswarp_pidfile" ] && {
-        [ "$1" ] && printf "ts-warp is running PID: %s: " `cat "$tswarp_pidfile"`
-        return 0
-    } || {
+    [ -s "$tswarp_pidfile" -a -r "$tswarp_pidfile" ] || {
         [ "$1" ] && printf "ts-warp is not running: "
         return 1
     }
+
+    pgrep -F "$tswarp_pidfile" > /dev/null 2>&1
+    case $? in
+        0)
+           [ "$1" ] && printf "ts-warp is running PID: %s: " `cat "$tswarp_pidfile"`
+           return 0
+           ;;
+        1)
+           [ "$1" ] && printf "ts-warp is not running: "
+           return 1
+           ;;
+        *)
+           [ "$1" ] && printf "ts-warp is not found: "
+           return 2
+           ;;
+    esac
 }
 
+# ------------------------------------------------------------------------------
 _stop() {
+    _check_root
     if [ $FORCE -eq 1 ]; then 
         printf "Stopping ts-warp with force: "
         [ -f "$tswarp_pidfile" ] && rm "$tswarp_pidfile"
         pkill ts-warp
     else
-        _status && {
-            _check_root
-            printf "Stopping ts-warp: "
-            [ -f "$tswarp_pidfile" ] &&  { 
-                cat "$tswarp_pidfile" | xargs kill -TERM || pkill ts-warp
-            }
-            while [ -s "$tswarp_pidfile" ] ; do sleep 1; done
-        } || 
-            printf "ts-warp is already stopped: "
+        _status
+        case $? in
+            0)
+                ;;
+            1)
+                printf "ts-warp is already stopped: "
+                return 0
+                ;;
+            2)
+                printf "ts-warp status unknown: requesting 'force stop': "
+                [ -f "$tswarp_pidfile" ] && rm "$tswarp_pidfile"
+                pkill ts-warp
+                ;;
+        esac
+
+        printf "Stopping ts-warp: "
+        [ -f "$tswarp_pidfile" ] && {
+            cat "$tswarp_pidfile" | xargs kill -TERM || pkill ts-warp
+        }
+        while [ -s "$tswarp_pidfile" ] ; do sleep 1; done
     fi
     /sbin/pfctl -f /etc/pf.conf
 }
 
+# ------------------------------------------------------------------------------
 _reload() {
     # Re-read configuration file on HUP signal
     _status && {
@@ -120,6 +157,7 @@ _reload() {
     }
 }
 
+# ------------------------------------------------------------------------------
 _restart() {
     _check_root
     printf "Restarting ts-warp: "
@@ -127,6 +165,7 @@ _restart() {
     _start $*
 }
 
+# ------------------------------------------------------------------------------
 _check_root() {
     [ `id -u` -ne 0 ] && { 
         printf "Fatal: You must be root to proceed\n"
@@ -134,6 +173,7 @@ _check_root() {
     }
 }
 
+# ------------------------------------------------------------------------------
 _usage() {
     printf "Usage:\n\tts-warp.sh start|restart [options]\n" 
     printf "\tts-warp.sh stop|reload|status\n"
